### ISSUE TITLE
scb::Bytes error not found

### ISSUE THREAD

**Issue by ghost** [RIscRIpt/rsc#1]
whats is  <scb/Bytes.h> ?

**Comment by ridzenis** [comment]
@marcelomelofreitas, https://github.com/RIscRIpt/scb

**Comment by ridzenis** [comment]
By default it assumes that `scb` solution is placed in `$(SolutionDir)..\scb\`.

So directory tree of these two (`rsc` and `scb`) solutions should look like:

```
+ \projects
|  + \rsc
|  + \scb
```
